// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Groups      string
	GroupsUsers string
	Orgs        string
	Stores      string
	Users       string
}{
	Groups:      "groups",
	GroupsUsers: "groups_users",
	Orgs:        "orgs",
	Stores:      "stores",
	Users:       "users",
}
